require:
  - rubocop-rails
AllCops:
  NewCops: disable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'db/data_schema.rb'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'config.ru'
    - 'db/seeds.rb'
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'routes/**/*.rb'
Layout/LineLength:
  Max: 80
  IgnoredPatterns:
    - 'key = '
    - 'pepper = '
Metrics/MethodLength:
  CountAsOne: ['array',  'hash']
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Rails/SkipsModelValidations:
  AllowedMethods: ['touch']
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test